### ISSUE TITLE
feedsomekeys error when loading (Win10, FF Nightly 43.0a1, vimperator fixup-nightly branch)

### ISSUE THREAD

**Issue by gregist** [vimpr/vimperator-plugins#81]
The status line is,

`sourcing file failed: ***\feedSomeKeys_3.js:319: SyntaxError: expected expression, got keyword 'let'`

**Comment by dfeng** [comment]
If I'm not mistaken, Firefox has deprecated `let blocks` (see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)).

I basically expanded each `let (foo) (bar)` into `let foo; bar`. e.g.

```javascript
  function or (list, func) {
    let [head,] = list;
    return(list.length && func(head) || or(list.slice(1), func));
  }
```

**Comment by laoyang945** [comment]
same here, but thanks to @dfeng , it's fixed manually

**Comment by jokogr** [comment]
On Firefox 41.0.2 for Linux, feedSomeKeys3.js from 74a5a87 seems to produce no errors, could you check it?

**Comment by matreex** [comment]
feedsomekeys.js error when it is loading, points: "253: SyntaxError: illegal character", feedsomekeys running on vimperator.v.3.1.2 / firefox.v.45.0.2, please fix it, thanks so much.

**Comment by jstetten** [comment]
Running the plugin updated on Sep 29, 2015, I get `
