### ISSUE TITLE
smooziee: Buffer undefined reference, FF 44.0, VIMP 3.11

### ISSUE THREAD

**Issue by alexzorin** [vimpr/vimperator-plugins#93]
Looks like that the plugin can no longer get a reference to the `Buffer` module [here](https://github.com/vimpr/vimperator-plugins/blob/master/_smooziee.js#L110) when calculating scrolling.

Not too sure how to get that handle back.

**Comment by gkatsev** [comment]
That's a vimperator issue actually. It has to do with the breaking changes in `const` and `let`.
A fix for this specifically has been merged in already: https://github.com/vimperator/vimperator-labs/pull/393

**Comment by gkatsev** [comment]
Speaking of which, I have a new version of vimperator out with the fix. It'll take a couple of days to get approved on AMO, though.

**Comment by alexzorin** [comment]
:+1:
